#!/usr/bin/env python3
"""
Daily Report Generator - Trading performance reports.

Generates daily/weekly/monthly trading reports.
"""

import sys
import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.tracker import TradingTracker
from core.metrics import MetricsCollector


def generate_daily_report(
    output_format: str = "markdown",
    days: int = 1,
    output_path: Optional[str] = None
) -> str:
    """
    Generate daily trading report.
    
    Args:
        output_format: 'markdown' or 'json'
        days: Number of days to include
        output_path: Output file path (optional)
        
    Returns:
        Report content as string
    """
    tracker = TradingTracker()
    collector = MetricsCollector(tracker)
    
    # Calculate date range
    end_date = datetime.now()
    start_date = end_date - timedelta(days=days)
    
    # Get metrics
    metrics = collector.calculate_metrics(start_date=start_date, end_date=end_date)
    daily_series = collector.get_daily_series(days=days)
    
    if output_format == "json":
        report = _generate_json_report(metrics, daily_series)
    else:
        report = _generate_markdown_report(metrics, daily_series)
    
    if output_path:
        Path(output_path).write_text(report)
        print(f"Report saved to: {output_path}")
    
    return report


def _generate_markdown_report(metrics, daily_series) -> str:
    """Generate markdown report."""
    lines = [
        "# Trading Performance Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Period:** {metrics.start_date.strftime('%Y-%m-%d') if metrics.start_date else 'N/A'} to {metrics.end_date.strftime('%Y-%m-%d') if metrics.end_date else 'N/A'}",
        "",
        "## Summary Statistics",
        "",
        f"- **Total Trades:** {metrics.total_trades}",
        f"- **Win Rate:** {metrics.win_rate:.2f}%",
        f"- **Net P&L:** ₹{metrics.net_pnl:,.2f}",
        f"- **Profit Factor:** {metrics.profit_factor:.2f}",
        f"- **Sharpe Ratio:** {metrics.sharpe_ratio:.2f}",
        "",
        "## Risk Metrics",
        "",
        f"- **Max Drawdown:** ₹{metrics.max_drawdown:,.2f} ({metrics.max_drawdown_pct:.2f}%)",
        f"- **Average Profit:** ₹{metrics.avg_profit:,.2f}",
        f"- **Average Loss:** ₹{metrics.avg_loss:,.2f}",
        f"- **Max Consecutive Wins:** {metrics.max_consecutive_wins}",
        f"- **Max Consecutive Losses:** {metrics.max_consecutive_losses}",
        "",
        "## Daily Performance",
        "",
        "| Date | Trades | P&L | Cumulative | Drawdown |",
        "|------|--------|-----|------------|----------|"
    ]
    
    for snapshot in daily_series:
        lines.append(
            f"| {snapshot.date} | {snapshot.trades} | "
            f"₹{snapshot.pnl:,.2f} | ₹{snapshot.cumulative_pnl:,.2f} | "
            f"₹{snapshot.drawdown:,.2f} |"
        )
    
    lines.extend([
        "",
        "---",
        "",
        "*Report generated by TradingBot*"
    ])
    
    return '\n'.join(lines)


def _generate_json_report(metrics, daily_series) -> str:
    """Generate JSON report."""
    data = {
        'generated_at': datetime.now().isoformat(),
        'metrics': {
            'total_trades': metrics.total_trades,
            'winning_trades': metrics.winning_trades,
            'losing_trades': metrics.losing_trades,
            'win_rate': round(metrics.win_rate, 2),
            'net_pnl': round(metrics.net_pnl, 2),
            'profit_factor': round(metrics.profit_factor, 2),
            'sharpe_ratio': round(metrics.sharpe_ratio, 2),
            'max_drawdown': round(metrics.max_drawdown, 2),
            'max_drawdown_pct': round(metrics.max_drawdown_pct, 2),
        },
        'daily_series': [
            {
                'date': s.date,
                'trades': s.trades,
                'pnl': round(s.pnl, 2),
                'cumulative_pnl': round(s.cumulative_pnl, 2),
                'drawdown': round(s.drawdown, 2)
            }
            for s in daily_series
        ]
    }
    
    return json.dumps(data, indent=2)


def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate trading performance report")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown",
                        help="Output format")
    parser.add_argument("--days", type=int, default=1,
                        help="Number of days to include")
    parser.add_argument("--output", type=str,
                        help="Output file path")
    
    args = parser.parse_args()
    
    report = generate_daily_report(
        output_format=args.format,
        days=args.days,
        output_path=args.output
    )
    
    if not args.output:
        print(report)


if __name__ == "__main__":
    main()
